using LinqToDB.Mapping;

namespace DataPitcher.Infrastructure.Persistence;

[Table("Jobs")] internal sealed class JobRow { [PrimaryKey, Column("JobId")] public string JobId { get; set; } = ""; [Column("RunId")] public string RunId { get; set; } = ""; [Column("PlanId")] public string PlanId { get; set; } = ""; [Column("IdempotencyKey")] public string IdempotencyKey { get; set; } = ""; [Column("State")] public string State { get; set; } = ""; [Column("CreatedUtc")] public string CreatedUtc { get; set; } = ""; [Column("UpdatedUtc")] public string UpdatedUtc { get; set; } = ""; [Column("FailureCode")] public string? FailureCode { get; set; } }
[Table("JobStateTransitions")] internal sealed class JobStateTransitionRow { [PrimaryKey, Column("TransitionId")] public string TransitionId { get; set; } = ""; [Column("JobId")] public string JobId { get; set; } = ""; [Column("FromState")] public string FromState { get; set; } = ""; [Column("ToState")] public string ToState { get; set; } = ""; [Column("OccurredUtc")] public string OccurredUtc { get; set; } = ""; }
[Table("JobLeases")] internal sealed class JobLeaseRow { [PrimaryKey, Column("JobId")] public string JobId { get; set; } = ""; [Column("OwnerId")] public string? OwnerId { get; set; } [Column("ExpiresUtc")] public string? ExpiresUtc { get; set; } [Column("FenceToken")] public long FenceToken { get; set; } }
[Table("BatchCheckpointMirrors")] internal sealed class BatchCheckpointMirrorRow { [PrimaryKey(0), Column("JobId")] public string JobId { get; set; } = ""; [PrimaryKey(1), Column("RunId")] public string RunId { get; set; } = ""; [Column("LastCommittedBatchSequence")] public long LastCommittedBatchSequence { get; set; } [Column("LastCommittedStableKey")] public string? LastCommittedStableKey { get; set; } [Column("CumulativeRowCount")] public long CumulativeRowCount { get; set; } [Column("SealedManifestHash")] public string SealedManifestHash { get; set; } = ""; [Column("FenceToken")] public long FenceToken { get; set; } [Column("UpdatedUtc")] public string UpdatedUtc { get; set; } = ""; }
[Table("ConnectionProfiles")] internal sealed class ConnectionProfileRow { [PrimaryKey, Column("ConnectionId")] public string ConnectionId { get; set; } = ""; [Column("DisplayName")] public string DisplayName { get; set; } = ""; [Column("ProviderId")] public string ProviderId { get; set; } = ""; [Column("SecretReferenceKind")] public string SecretReferenceKind { get; set; } = ""; [Column("SecretReferenceLocator")] public string SecretReferenceLocator { get; set; } = ""; [Column("BusinessSchema")] public string BusinessSchema { get; set; } = ""; [Column("StagingSchema")] public string StagingSchema { get; set; } = ""; [Column("Version")] public long Version { get; set; } [Column("HealthState")] public string HealthState { get; set; } = ""; [Column("AssessmentMode")] public string? AssessmentMode { get; set; } [Column("AssessmentRole")] public string? AssessmentRole { get; set; } [Column("DatabaseIdentity")] public string? DatabaseIdentity { get; set; } [Column("ProviderVersion")] public string? ProviderVersion { get; set; } [Column("CapabilitiesJson")] public string? CapabilitiesJson { get; set; } [Column("CleanupFailureCode")] public string? CleanupFailureCode { get; set; } [Column("CreatedUtc")] public string CreatedUtc { get; set; } = ""; [Column("UpdatedUtc")] public string UpdatedUtc { get; set; } = ""; [Column("IdempotencyKey")] public string IdempotencyKey { get; set; } = ""; }
[Table("SchemaScans")] internal sealed class SchemaScanRow { [PrimaryKey, Column("ScanId")] public string ScanId { get; set; } = ""; [Column("ConnectionId")] public string ConnectionId { get; set; } = ""; [Column("IdempotencyKey")] public string IdempotencyKey { get; set; } = ""; [Column("State")] public string State { get; set; } = ""; [Column("SnapshotId")] public string? SnapshotId { get; set; } [Column("SnapshotHash")] public string? SnapshotHash { get; set; } [Column("FailureCode")] public string? FailureCode { get; set; } [Column("CreatedUtc")] public string CreatedUtc { get; set; } = ""; [Column("UpdatedUtc")] public string UpdatedUtc { get; set; } = ""; }
[Table("SchemaSnapshots")] internal sealed class SchemaSnapshotRow { [PrimaryKey, Column("SnapshotId")] public string SnapshotId { get; set; } = ""; [Column("ConnectionId")] public string ConnectionId { get; set; } = ""; [Column("SnapshotHash")] public string SnapshotHash { get; set; } = ""; [Column("ContentJson")] public string ContentJson { get; set; } = ""; [Column("CreatedUtc")] public string CreatedUtc { get; set; } = ""; }
[Table("Selections")] internal sealed class SelectionRow { [PrimaryKey, Column("SelectionId")] public string SelectionId { get; set; } = ""; [Column("DisplayName")] public string DisplayName { get; set; } = ""; [Column("QueryJson")] public string QueryJson { get; set; } = ""; [Column("Version")] public long Version { get; set; } [Column("CreatedUtc")] public string CreatedUtc { get; set; } = ""; [Column("UpdatedUtc")] public string UpdatedUtc { get; set; } = ""; }
[Table("Plans")] internal sealed class PlanRow { [PrimaryKey, Column("PlanId")] public string PlanId { get; set; } = ""; [Column("DisplayName")] public string DisplayName { get; set; } = ""; [Column("OperatorNote")] public string? OperatorNote { get; set; } [Column("Version")] public long Version { get; set; } [Column("CanonicalHash")] public string? CanonicalHash { get; set; } [Column("CreatedUtc")] public string CreatedUtc { get; set; } = ""; [Column("UpdatedUtc")] public string UpdatedUtc { get; set; } = ""; }
