<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><TargetFramework>net10.0</TargetFramework><RootNamespace>DataPitcher.Providers.SqlServer</RootNamespace></PropertyGroup><ItemGroup><ProjectReference Include="../DataPitcher.Core/DataPitcher.Core.csproj" /><ProjectReference Include="../DataPitcher.Infrastructure/DataPitcher.Infrastructure.csproj" /><PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" /></ItemGroup></Project>
