CREATE TABLE JobEventStreams (JobId TEXT NOT NULL PRIMARY KEY, NextEventId INTEGER NOT NULL, OldestAvailableEventId INTEGER NOT NULL);
CREATE TABLE JobEvents (JobId TEXT NOT NULL, EventId INTEGER NOT NULL, EventType TEXT NOT NULL, State TEXT NOT NULL, RowsTransferred INTEGER NOT NULL, BytesTransferred INTEGER NOT NULL, OccurredUtc TEXT NOT NULL, PRIMARY KEY (JobId, EventId));
